select * from customer_data;

SELECT 
    category,
    COUNT(*) AS total_orders,
    SUM(purchase_amount_usd) AS total_revenue,
    AVG(purchase_amount_usd) AS avg_order_value
FROM customer_data
GROUP BY category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by male versus female customers?

select gender,
 sum(purchase_amount_usd) as total_revenue 
 from customer_data 
 group by gender;

-- Which customers used a discount but still spent more than the overall average purchase amount?

select customer_id,
 purchase_amount_usd 
 from customer_data 
 where discount_applied = "Yes" 
 and 
 purchase_amount_usd >= (select avg(purchase_amount_usd) from customer_data);
 
 -- Which are the top 5 products with the highest average review rating?

select item_purchased as products, avg(review_rating) from customer_data group by item_purchased order by avg(review_rating) desc limit 5;

-- How does the average purchase amount compare between Standard and Express shipping types?

select shipping_type, avg(purchase_amount_usd) from customer_data where shipping_type in("Standard","Express") group by shipping_type;

-- Do subscribed customers spend more? Compare average spending and total revenue between subscribed and non-subscribed customers.

select subscription_status, count(*) as total_transactions, avg(purchase_amount_usd) as average_spending, sum(purchase_amount_usd) as total_revenue from customer_data group by subscription_status;

-- Which five products have the highest percentage of purchases where a discount was applied?

select item_purchased, count(*), sum(case when discount_applied = "Yes" then 1 else 0 end) as discount_purchases,     
    round((sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*)) * 100,2) as discount_percentage from customer_data group by item_purchased order by discount_percentage desc limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number 
-- of previous purchases, and show the count of customers in each segment.

select (case when previous_purchases = 1 then "New" when previous_purchases between 2 and 10 then "Returning" else "loyal" end) as customer_segment, count(*) from customer_data group by customer_segment;

-- What are the top 3 most purchased products within each category?

SELECT *
FROM (
        SELECT
            category,
            item_purchased,
            COUNT(*) AS purchase_count,
            
            ROW_NUMBER() OVER (
                PARTITION BY category
                ORDER BY COUNT(*) DESC
            ) AS ranking
            
        FROM customer_data
        GROUP BY category, item_purchased
     ) AS ranked_products
WHERE ranking <= 3;

-- Are repeat buyers (customers with more than five previous purchases) more likely to subscribe?

SELECT
    CASE 
        WHEN previous_purchases > 10 THEN 'Repeat Buyers'
        ELSE 'Others'
    END AS customer_group,

    COUNT(*) AS total_customers,

    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers,

    100.0 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) 
        AS subscription_rate
FROM customer_data
GROUP BY customer_group;

-- (Or)

select subscription_status,count(customer_id) as subscribers from customer_data where previous_purchases>5 group by subscription_status;

-- What is the revenue contribution of each age group?

select age_group, sum(purchase_amount_usd) as revenue from customer_data group by age_group order by revenue desc;